Updates to case sensitivity and "nag" captiveOption
Sonoran-Software/sonoran_forcereg pull request #2
Opened 2020-06-14 15:58 UTC by Blizzard098

I have made it so the "nag" captiveOption has two sub-options for where to display the text: Center or Top. With this, I have centered the drawText a bit more. I have also made it so all captiveOptions are now non-case sensitive :)

_I did not edit the version number as I am not sure what you have planned for versions._

2020-06-14 16:02 UTC, Blizzard098 commented
Sorry about the mistake with one of the commits. If you need to read the file to see the changes better, here ya go: https://github.com/Blizzard098/sonoran_forcereg/blob/master/forcereg/cl_forcereg.lua

2020-06-15 00:15 UTC, SonoranBrian commented on forcereg/CHANGEMEconfig_forcereg.lua
> +    enabled = true,
Default plugin config should show enabled as false

2020-06-15 01:31 UTC, nathanctech requested changes

2020-06-15 01:31 UTC, nathanctech commented on forcereg/CHANGEMEconfig_forcereg.lua
> +    enabled = true,
Agreed, default config needs to be disabled.

2020-06-15 01:31 UTC, nathanctech commented on forcereg/CHANGEMEconfig_forcereg.lua
> +    captiveOption = "Nag",
Not strictly needed, lua is case insensitive despite the comment above being uppercased. Seems fine, though.

2020-06-15 01:31 UTC, nathanctech commented on forcereg/cl_forcereg.lua
> +            if pluginConfig.captiveOption:lower() == "nag" then
Not needed if the above config is left lowercase. Is there a reason for this since adding `lower` just adds complexity?

2020-06-15 20:54 UTC, Blizzard098 commented on forcereg/cl_forcereg.lua
> +            if pluginConfig.captiveOption:lower() == "nag" then
Yeah sorry I thought Lua was case sensitive with strings. My bad.

2020-06-15 20:54 UTC, Blizzard098 commented on forcereg/CHANGEMEconfig_forcereg.lua
> +    enabled = true,
Yeah sorry forgot to set it back to false.

2020-06-15 20:54 UTC, Blizzard098 commented on forcereg/CHANGEMEconfig_forcereg.lua
> +    captiveOption = "Nag",
See other comment.

2020-06-15 21:00 UTC, Blizzard098 commented
Made requested edits. My apologies again, thought Lua was case sensitive.

2020-06-15 21:04 UTC, nathanctech approved these changes

2020-06-15 21:05 UTC, merged